Revert "mageia and oraclelinux don't have `dwarves` package"
This reverts commit c390825317ea47626d1924a01880b431454bb405.

```
RPM build warnings:
	dwarves is needed by kernel-6.7.0_20240309-2.x86_64
    line 34: It's not recommended to have unversioned Obsoletes: Obsoletes: kernel-headers
```

```
error: Failed build dependencies:
	dwarves is needed by kernel-6.7.0_20240309-2.x86_64
Building target platforms: x86_64-linux
```