disable parrot
builddeps:linux : Depends: kernel-wedge (>= 2.105~) but 2.104 is to be installed

```
------
 > [parrot  9/15] RUN apt-get build-dep -y linux:
0.454 Reading state information...
0.493 Some packages could not be installed. This may mean that you have
0.493 requested an impossible situation or if you are using the unstable
0.493 distribution that some required packages have not yet been created
0.493 or been moved out of Incoming.
0.493 The following information may help to resolve the situation:
0.493
0.493 The following packages have unmet dependencies:
0.538  builddeps:linux : Depends: kernel-wedge (>= 2.105~) but 2.104 is to be installed
0.541 E: Unable to correct problems, you have held broken packages.
------
Error: Process completed with exit code 17.
```